# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/digilent-xdc/Arty-Z7-10-Master.xdc

# IP: ip/vio_1/vio_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vio_1 || ORIG_REF_NAME==vio_1} -quiet] -quiet
